---
#all

- hosts: all
  #connection: local
  become: true
  tasks:

  - name: add user bot
    user:
      name: bot
      system: yes
      groups: root
  
  - name: add ssh key for bot #key to be changed for every newly deployed server that provisions the infrastructure
    authorized_key:
      user: bot
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP+ADldotae0+9tcMHqaR/ICXvq20r4PEG2ZXy5ppNUq ansible dedicated


  - name: add ansible-pull cron job
    cron:
      name: ansible provisioning 
      user: bot
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/simonebenati/ansible-server.git


#web_servers

- hosts: web_servers
  become: true
  tasks:

    - name: Install web servers packages
      apt: 
        name: 
          - apache2
          - vim-nox
          - python3-psutil
          - docker


#file_servers

- hosts: file_servers
  become: true
  tasks:

    - name: Install file servers packages
      apt:
        name:
          - vim-nox
          - python3-psutil
          - samba