---
#all

- hosts: all
  #connection: local
  become: true
  tasks:

  - name: add user bot
    user:
      name: bot
      system: yes

  - name: setup sudo for bot
    copy:
      src: files/sudoerz
      dest: /etc/sudoers.d/bot
      owner: root
      group: root
      mode:  0440

  - name: add ansible-pull cron job
    cron:
      name: ansible provisioning 
      user: bot
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/simonebenati/ansible-server.git


#web_servers

- hosts: web_servers
  become: true
  tasks:

    - name: Install web servers packages
      apt: 
        name: 
          - apache2
          - vim-nox
          - python3-psutil
          - docker


#file_servers

- hosts: file_servers
  become: true
  tasks:

    - name: Install file servers packages
      apt:
        name:
          - vim-nox
          - python3-psutil
          - samba