---

#web_servers

- hosts: web_servers
  become: true
  tasks:

    - name: Install web servers packages
      apt: 
        name: 
          - apache2
          - vim-nox
          - python3-psutil
          - docker


#file_servers

- hosts: file_servers
  become: true
  tasks:

    - name: Install file servers packages
      apt:
        name:
          - vim-nox
          - python3-psutil
          - samba